language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: target/site/scaladocs
  keep-history: true
  verbose: true
  github-token: "$GH_TOKEN"
  on:
    branch: master
env:
  global:
    secure: mlEQNGjrtwuuOox+1jPYCM6gFpXqexzkAVrW4825xXXZ01UBB+3Upkewg+r3zx7Sx/dzAAFPLxgrMoloHSuzUTpnz1z2RgU2KjHatguZd4pU8pB9EB+y06vknWDgrxt3z+RNoL+sn1zVO0751r4shHrQI9XhAtk5+h7DUggkwTvL/4uQRmJRQuPYZjMU8fw4lo0tGcMi4Ulaix9ZZqF6YziW1fdSn1T4c5wQdrmSMvVONxxkTA+2SmzFwGK1vmxLfheBBzNaITSplOhBlTilk9sLMEKsX8ya6Nc4g/+CRPUkkWvEALAfML7GS7FoXuB5jE9r962EThSuphniDWvXI7uHrH/jprjEY5e9GcV7WyUDZh134dH9nTNDzqolOhqVGOpKm/YfrtBRD3rJtXoGKEtwDVZzDRJqRbDOtc3/N3QWl9O5wEiV9FJwezAry9EHIYp9K4H50zXROAcyNv1s0BfzUUmhySiV/QhFNVVhR4C6Ctp8k2eirnFzA9yaQ8h7twUUXbdC5XzVxpHrVG74JWH581Kc3KTTvrHbtMmI7A19spXyXrDoTOp+VqJs5Gl8t+InicPNtd7gQxFwJSp//g5ktjhe+f6ld97QPMopy5q7QBXZVZZbvUOy0YZSwtkuX0XIs0W8gfkUGkoxys1RM6SA1yUK8tKdHGt+99ywXAQ=
